news/urls.py
from django.urls import path

from . import views

app_name = "news"
urlpatterns = [
    path('', views.newsindex),
    path('<int:id>/<slug:post_slug>/', views.news_post_detail_view, name='post_detail'),
]

news/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone

from unidecode import unidecode


class Post(models.Model):
    post_title = models.CharField(verbose_name="Заголовок", max_length=100)
    post_short_description = models.CharField(verbose_name="Краткое описание", max_length=100, blank=True)
    post_full_description = models.TextField(verbose_name="Описание", max_length=5000)
    post_author = models.CharField(verbose_name="Автор", max_length=20)
    post_publication_date = models.DateTimeField(verbose_name="Дата публикации", default=timezone.now)
    post_slug = models.SlugField(default="", unique=True, editable=False, max_length=100)
    post_is_active = models.BooleanField(verbose_name="Активно", default=True)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def save(self, *args, **kwargs):
        self.post_slug = slugify(unidecode(self.post_title))
        super(Post, self).save()

    def __str__(self):
        return self.post_title

news/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post


def newsindex(request):
    post_list = Post.objects.order_by("-post_publication_date").all()
    paginator = Paginator(post_list, 10)
    page = request.GET.get("page")
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    context = {
        "post_list": post_list,
    }
    return render(request, "news/index.html", context=context)


def news_post_detail_view(request, post_slug, id):
    post = get_object_or_404(Post, pk=id)
    context = {
        "post": post,
    }
    return render(request, template_name="news/post_detail_view.html", context=context)

news/templates/news/index.html
{% extends "base.html" %}

{% block title %}Новости{% endblock %}

{% block content %}


    {% if post_list %}
        <div class="news_list">
            <ul>
                {% for post in post_list %}
                    <div class="news">
                        <li><a
                                href="{% url 'news:post_detail' post.id post.post_slug %}">{{ post.post_title|safe }}</a>
                            <div>{{ post.post_short_description }}</div>
                            <div class="news_info">Дата: <b>{{ post.post_publication_date|date:"d.m.Y H:i" }}</b> |
                                Автор: <b>{{ post.post_author }}</b>
                            </div>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>

        <nav aria-label="post_list">
            <ul class="pagination">

                {% if post_list.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ post_list.previous_page_number }}">Назад</a>
                    </li>
                {% endif %}

                {% for num in post_list.paginator.page_range %}
                    {% if num == post_list.number %}
                        <li class="page-item active" aria-current="page"><span class="page-link">{{ num }} <span
                                class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}"> <b>{{ num }}</b> </a></li>
                    {% endif %}
                {% endfor %}

                {% if post_list.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ post_list.next_page_number }}">
                        Далее
                    </a></li>
                {% endif %}

            </ul>
        </nav>

    {% else %}
        <p>В данный момент новостей нет.</p>
    {% endif %}

{% endblock %}

news/templates/news/post_detail_view.html
{% extends "base.html" %}

{% block title %}{{ post.post_title }}{% endblock %}


{% block content %}

    <h1 class="text-center">{{ post.post_title }}</h1>
    <p> {{ post.post_full_description|safe }}</p>

    <div class="news">
        <div class="news_info">Дата: <b>{{ post.post_publication_date|date:"d.m.Y H:i" }}</b> |
            Автор: <b>{{ post.post_author }}</b>
        </div>
    </div>

{% endblock %}