news/urls.py
from django.urls import path

from . import views

app_name = "news"
urlpatterns = [
    path('', views.newsindex),
    path('<int:id>/<slug:post_slug>/', views.news_post_detail_view, name='post_detail'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "project"
urlpatterns = [
    path('', views.project_index, name='projects_list'),
    path('add/', views.project_add, name='project_add'),
    path('<int:id>/<slug:project_slug>/', views.project_detail_view, name='detail'),
    path('news/<int:id>/', views.project_news_detail_view, name='project_news_detail'),
    path('tasks/<int:id>/', views.project_tasks_view, name='project_tasks_view'),
    path('tasks/<int:id>/view/', views.tasks_task_view, name='task_view'),
    path('tasks/<int:id>/edit/', views.tasks_task_edit, name='task_edit'),
]

projects/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone

from unidecode import unidecode
#123

class Project(models.Model):
    project_name = models.CharField(verbose_name="Название проекта", max_length=50)
    project_short_description = models.CharField(verbose_name="Краткое описание", max_length=100)
    project_full_description = models.CharField(verbose_name="Полное описание", max_length=5000)
    project_publication_date = models.DateTimeField(verbose_name="Дата публикации", auto_now_add=True)
    project_author = models.CharField(verbose_name="Автор", max_length=15)
    project_slug = models.SlugField(default="", unique=True, editable=False)

    class Meta:
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"

    def save(self, *args, **kwargs):
        self.project_publication_date = timezone.now()
        self.project_slug = slugify(unidecode(self.project_name))
        super(Project, self).save()

    def __str__(self):
        return self.project_name


class Tasks(models.Model):
    tracker_choices = ("Bug", "Bug"), ("Feature", "Feature"), ("Support", "Support")
    priority_choices = ("Low", "Low"), ("Normal", "Normal"), ("High", "High"), ("Urgent", "Urgent"), (
        "Immediate", "Immediate")
    prepared_choices = [(str(i), str(i) + "%") for i in range(0, 110, 10)]  # 0-100%
    status_choices = ("New", "New"), ("In Progress", "In Progress"), ("Closed", "Closed")

    tasks_project_id = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="Проект", null=True, blank=True)
    tasks_tracker = models.CharField(verbose_name="Трекер", choices=tracker_choices, default="Bug", max_length=50)
    tasks_title = models.CharField(verbose_name="Тема", max_length=100)
    tasks_description = models.TextField(verbose_name="Описание", max_length=5000, blank=True)
    tasks_status = models.CharField(verbose_name="Статус", choices=status_choices, default="New", max_length=50)
    tasks_priority = models.CharField(verbose_name="Приоритет", choices=priority_choices, default="Normal",
                                      max_length=50)
    tasks_assigned = models.CharField(verbose_name="Назначена", max_length=50, blank=True)
    tasks_category = models.CharField(verbose_name="Категория", default="", max_length=50, blank=True)
    tasks_files = models.FileField(verbose_name="Файлы", upload_to="uploads/", blank=True)
    tasks_start_date = models.DateField(verbose_name="Начало выполнения")
    tasks_complete_date = models.DateField(verbose_name="Дата выполнения", null=True, blank=True)
    tasks_time_evaluation = models.IntegerField(verbose_name="Кол-во часов", default=0, blank=True)
    tasks_prepared = models.CharField(verbose_name="Готовность", choices=prepared_choices, default=0, max_length=50,
                                      blank=True)

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

    def save(self, *args, **kwargs):
        super(Tasks, self).save()

    def __str__(self):
        return self.tasks_title

    def __unicode__(self):
        return self.tasks_project_id


class News(models.Model):
    news_project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    news_title = models.CharField(verbose_name="Заголовок", max_length=50)
    news_summary = models.CharField(verbose_name="Краткое описание", max_length=100)
    news_description = models.CharField(verbose_name="Описание", max_length=1000)
    news_author = models.CharField(verbose_name="Автор", max_length=20)
    news_created_on = models.DateField(verbose_name="Дата публикации")
    news_project_slug = models.SlugField(default="", unique=True, editable=False)

    def save(self, *args, **kwargs):
        self.news_project_slug = slugify(unidecode(self.news_title))
        super(News, self).save()

    def __str__(self):
        return self.news_title

projects/forms.py
from django import forms
from projects.models import Tasks, Project


class TaskAddForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['tasks_project_id', 'tasks_tracker', 'tasks_title', 'tasks_description', 'tasks_status',
                  'tasks_priority', 'tasks_start_date']


class ProjectAddForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_name', 'project_short_description', 'project_full_description', 'project_author']


class TaskEditForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = '__all__'

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from projects.models import Project, Tasks, News
from projects.forms import TaskAddForm, ProjectAddForm, TaskEditForm


def project_index(request):  # Список проектов
    project_list = Project.objects.order_by("-project_publication_date").all()
    project_count = len(project_list)  # Количество проектов
    paginator = Paginator(project_list, 10)  # max: 10
    page = request.GET.get("page")
    try:
        project_list = paginator.page(page)
    except PageNotAnInteger:
        project_list = paginator.page(1)
    except EmptyPage:
        project_list = paginator.page(paginator.num_pages)
    context = {
        "project_list": project_list,
        "project_count": project_count,  # Количество проектов
    }
    return render(request, template_name="projects/index.html", context=context)


def project_detail_view(request, project_slug, id):
    project = get_object_or_404(Project, pk=id)
    project_name = Project.objects.get(id=id).project_name  # Вывод имени текущего проекта

    try:
        news_project_list = News.objects.all().filter(news_project_id=id)  # Список новостей для текущего проекта
        news_count_list = len(news_project_list)
    except News.DoesNotExist:
        news_project_list = "Нет новостей"

    try:
        tasks_project_list = Tasks.objects.all().filter(tasks_project_id=id)  # Список задач для текущего проекта
        countlist = len(tasks_project_list)  # Счетчик задач для текущего проекта
        bug_list = len(Tasks.objects.filter(tasks_tracker__contains="Bug",
                                            tasks_project_id=id))  # Количество "Bug" в задачах для текущего проекта
        feature_list = len(Tasks.objects.filter(tasks_tracker__contains="Feature",
                                                tasks_project_id=id))  # Количество "Feature" в задачах для текущего проекта
        support_list = len(Tasks.objects.filter(tasks_tracker__contains="Support",
                                                tasks_project_id=id))  # Количество "Support" в задачах для текущего проекта
    except Tasks.DoesNotExist:
        tasks_project_list = "Задач нет"

    context = {
        "project": project,
        "project_name": project_name,  # Вывод имени текущего проекта
        "news_project_list": news_project_list,  # Список новостей для текущего проекта
        "tasks_project_list": tasks_project_list,  # Список задач для текущего проекта
        "countlist": countlist,  # Счетчик задач для текущего проекта
        "bug_list": bug_list,  # Количество "Bug" в задачах для текущего проекта
        "feature_list": feature_list,  # Количество "Feature" в задачах для текущего проекта
        "support_list": support_list,  # Количество "Support" в задачах для текущего проекта
        "news_count_list": news_count_list,
    }
    return render(request, template_name="projects/detail.html", context=context)


def project_news_detail_view(request, id):
    news = get_object_or_404(News, pk=id)
    context = {
        "news": news,
    }
    return render(request, template_name="projects/project_news_detail.html", context=context)


def project_tasks_view(request, id):  # Вывод количества задач для текущего проекта
    project = get_object_or_404(Project, pk=id)
    project_name = Project.objects.get(id=id).project_name
    tasks_list = Tasks.objects.all().filter(tasks_project_id=id)
    context = {
        "project_name": project_name,
        "tasks_list": tasks_list,
    }
    return render(request, template_name="projects/project_tasks_view.html", context=context)


def task_list_show(request):  # Вывод всех задач в базе на странице >>>http://phoenixfk.ru
    task_list = Tasks.objects.order_by("id").reverse().all()
    task_count = len(task_list)  # Счетчик количества задач
    paginator = Paginator(task_list, 10)  # max: 10
    page = request.GET.get("page")
    try:
        task_list = paginator.page(page)
    except PageNotAnInteger:
        task_list = paginator.page(1)
    except EmptyPage:
        task_list = paginator.page(paginator.num_pages)
    context = {
        "task_list": task_list,
        "task_count": task_count,
    }
    return render(request, "projects/tasks_list.html", context=context)


@login_required
def task_add(request):
    get_project_list = Project.objects.order_by("project_name")
    if request.method == 'POST':
        form = TaskAddForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.tasks_assigned = request.user
            form.save()
            return redirect("tasklist")
    else:
        form = TaskAddForm()
    return render(request, "projects/tasks_add.html", {"form": form, "get_project_list": get_project_list})


@login_required
def project_add(request):
    if request.method == 'POST':
        form = ProjectAddForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.project_author = request.user
            project.project_publication_date = timezone.now()
            form.save()
            return redirect("project:projects_list")
    else:
        form = ProjectAddForm()
    return render(request, "projects/project_add.html", {"form": form})


def tasks_task_view(request, id):  # Вывод количества задач для текущего проекта
    task = get_object_or_404(Tasks, pk=id)
    task_name = Tasks.objects.get(id=id).tasks_title
    context = {
        "task": task,
        "task_name": task_name,
    }
    return render(request, template_name="projects/tasks_view_task.html", context=context)


@login_required
def tasks_task_edit(request, id):
    task = get_object_or_404(Tasks, pk=id)
    form = TaskEditForm(request.POST, instance=task)
    if request.method == 'POST':
        if form.is_valid():
            task = form.save(commit=False)
            form.save()
            return redirect("tasklist")
    else:
        form = TaskEditForm()
    return render(request, "projects/tasks_edit.html",
                  {"form": form,
                   "task": task,
                   })


# AUTH

def logout_view(request):
    logout(request)
    return redirect('/')


def auth_login(request):
    return redirect('/')


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, "register.html", {"form": form})

projects/templates/projects/detail.html
{% extends "base.html" %}

{% block title %}{{ project.project_name }}{% endblock %}


{% block content %}

    <h1 style="text-align: center">{{ project.project_name }}</h1>
    <p>{{ project.project_full_description }}</p>
    Автор: <b>{{ project.project_author }}</b>
    <hr>
    Последние пять новостей проекта <b>{{ project.project_name }}</b>:
    {% if news_count_list == 0 %}
        Новостей нет
    {% else %}
    {% endif %}
    {% if news_project_list %}
        {% for news in news_project_list %}
            <li>
                <a href="{% url 'project:project_news_detail' news.id %}">{{ news.news_title|safe }}</a>
            </li>
        {% endfor %}
        <button type="button" class="btn btn-info">Посмотреть все новости</button>
    {% endif %}

    <hr>

    {% if countlist == 0 %}
        Задачи: <b>0</b> <br>
        <a href="/projects/">
            <button type="button" class="btn btn-info">Назад</button>
        </a>

    {% else %}
        Задачи: <a href="{% url 'project:project_tasks_view' project.id %}"><b>{{ countlist }}</b></a>  из них:

        <li>Bug: <b>{{ bug_list }}</b></li>
        <li>Feature: <b>{{ feature_list }}</b></li>
        <li>Support: <b>{{ support_list }}</b></li>

        <a href="{% url 'project:project_tasks_view' project.id %}">
            <button type="button" class="btn btn-info">Посмотреть все задачи</button>
        </a>
        <a href="/projects/">
            <button type="button" class="btn btn-info">Назад</button>
        </a>
    {% endif %}
{% endblock %}

projects/templates/projects/index.html
{% extends "base.html" %}

{% block title %}Проекты{% endblock %}

{% block content %}

    Всего проектов: <b>{{ project_count }}</b>
    {% if request.user.is_authenticated %}
        |<a href="{% url 'project:project_add' %}">
        <button type="button" class="btn btn-success">Добавить проект</button>
    {% endif %}
</a>

    {% if project_list %}

        <ul>
            {% for project in project_list %}
                <li><a
                        href="{% url 'project:detail' project.id project.project_slug %}">{{ project.project_name|safe }}</a>
                    <br>{{ project.project_short_description }}
                    <div class="news_info">Дата: <b>{{ project.project_publication_date|date:"d.m.Y" }}</b> |
                        Автор: <b>{{ project.project_author }}</b>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <nav aria-label="project_list">
            <ul class="pagination">

                {% if project_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ project_list.previous_page_number }}">Назад</a>
                    </li>
                {% endif %}

                {% for num in project_list.paginator.page_range %}
                    {% if num == project_list.number %}
                        <li class="page-item active" aria-current="page"><span class="page-link">{{ num }} <span
                                class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}"> <b>{{ num }}</b> </a></li>
                    {% endif %}
                {% endfor %}

                {% if project_list.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ project_list.next_page_number }}">
                        Далее
                    </a></li>
                {% endif %}

            </ul>
        </nav>

    {% else %}
        <p>В данный момент проекты отсутствуют.</p>
    {% endif %}

{% endblock %}

projects/templates/projects/project_add.html
{% extends "base.html" %}

{% block title %}Добавить проект{% endblock %}


{% block content %}
    <form method="POST">{% csrf_token %}

        <div class="form-group col-md-4">
            <label for="id_project_name">Название проекта:</label><span style="color: red">*</span>
            <input type="text" name="project_name" class="form-control" id="id_project_name" maxlength="50" required>
        </div>

        <div class="form-group col-md-4">
            <label for="id_project_short_description">Краткое описание:</label><span style="color: red">*</span>
            <input type="text" name="project_short_description" class="form-control" id="id_project_short_description"
                   maxlength="100" required>
        </div>

        <div class="form-group col-md-4">
            <label for="id_project_full_description">Полное описание:</label><span style="color: red">*</span>
            <input type="text" name="project_full_description" class="form-control" id="id_project_full_description"
                   maxlength="5000" required>
        </div>

        <div class="form-group col-md-4">
            <label for="id_project_author">Автор:</label><span style="color: red">*</span>
            <input type="text" readonly name="project_author" class="form-control" id="id_project_author"
                   required value={{ user.username }}>
        </div>

        <a href="{% url 'project:projects_list' %}">
            <button type="button" class="btn btn-info">Назад</button>
        </a>
        <button type="submit" class="btn btn-success">Добавить</button>


    </form>

{% endblock %}

projects/templates/projects/project_news_detail.html
{% extends "base.html" %}

{% block title %} {% endblock %}


{% block content %}

    <h1 class="text-center">{{ news.news_title }}</h1>
    <p> Summary: {{ news.news_summary }}</p>
    <p> {{ news.news_description|safe }}</p>

    <div class="news">
        <div class="news_info">Дата: <b>{{ news.news_created_on|date:"d.m.Y" }}</b> |
            Автор: <b>{{ news.news_author }}</b>
        </div>
    </div>

{% endblock %}

projects/templates/projects/project_tasks_view.html
{% extends "base.html" %}

{% block title %}Задачи проекта - {{ project_name }}{% endblock %}


{% block content %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'taskadd' %}">
            <button type="button" class="btn btn-success">Добавить задачу</button>
        </a>
    {% endif %}
    {% if tasks_list %}

        <div class="table-responsive-sm">

            <table class="table table-sm table-hover">
                <thead class="thead-light">
                <tr>
                    <th style="text-align:center" scope="col">#</th>
                    <th style="text-align:center" scope="col">Трекер</th>
                    <th style="text-align:center" scope="col">Статус</th>
                    <th style="text-align:center" scope="col">Описание</th>
                    <th style="text-align:center" scope="col">Категория</th>
                    <th style="text-align:center" scope="col">Затраченное время</th>
                    <th style="text-align:center" scope="col">Готовность</th>
                </tr>
                </thead>
                <tbody>

                {% for tasks in tasks_list %}
                    <tr>
                        <th style="text-align:center" scope="row"><a href="#">{{ tasks.pk }}</a></th>
                        <td style="text-align:center">{{ tasks.tasks_tracker }}</td>
                        <td style="text-align:center">{{ tasks.tasks_status }}</td>
                        <td style="text-align:center"><a href="#">{{ tasks.tasks_title }}</a></td>
                        <td style="text-align:center">{{ tasks.tasks_category }}</td>
                        <td style="text-align:center">{{ tasks.tasks_time_evaluation }} ч.</td>
                        <td style="text-align:center">{{ tasks.tasks_prepared }}%</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

        </div>

    {% endif %}

{% endblock %}

projects/templates/projects/tasks_add.html
{% extends "base.html" %}

{% block title %}Добавить задачу{% endblock %}


{% block content %}
    <form method="POST">{% csrf_token %}
        <div class="form-group col-md-4">
            {% if get_project_list %}
                <label for="id_tasks_project_id">Проект:</label>
                <select name="tasks_project_id" id="id_tasks_project_id" class="form-control">
                    <option value="" selected>---------</option>
                    {% for project in get_project_list %}
                        <option value="{{ project.pk }}">{{ project.project_name }}</option> {# value 1 - Phoenix #}
                    {% endfor %}
                </select>
            {% endif %}
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_tracker">Трекер:</label><span style="color: red">*</span>
            <select name="tasks_tracker" id="id_tasks_tracker" class="form-control">
                <option>Bug</option>
                <option>Feature</option>
                <option>Support</option>
            </select>
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_title">Тема:</label><span style="color: red">*</span>
            <input type="text" name="tasks_title" class="form-control" id="id_tasks_title" maxlength="100" required>
        </div>

        <div class="form-group col-md-10">
            <label for="id_tasks_description">Описание:</label>
            <input type="text" name="tasks_description" class="form-control" id="id_tasks_description" maxlength="5000">
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_status">Статус:</label><span style="color: red">*</span>
            <input type="text" readonly name="tasks_status" class="form-control" id="id_tasks_status" value="New"
                   maxlength="50" required>
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_priority">Приоритет:</label><span style="color: red">*</span>
            <select name="tasks_priority" id="id_tasks_priority" class="form-control">
                <option>Low</option>
                <option selected>Normal</option>
                <option>High</option>
            </select>
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_assigned">Автор:</label><span style="color: red">*</span>
            <input type="text" readonly name="tasks_assigned" class="form-control" id="id_tasks_assigned"
                   required value={{ user.username }}>
        </div>

        <div class="form-group col-md-4">
            <label for="id_tasks_start_date">Дата начала:</label><span style="color: red">*</span>
            <input type="date" name="tasks_start_date" value="{% now 'Y-m-d' %}" class="form-control"
                   id="id_tasks_start_date" required>
        </div>

        <a href="{% url 'tasklist' %}">
            <button type="button" class="btn btn-info">Назад</button>
        </a>
        <button type="submit" class="btn btn-success">Добавить</button>

    </form>

{% endblock %}

projects/templates/projects/tasks_edit.html
{% extends "base.html" %}

{% block title %}Задача №{{ task.pk }}{% endblock %}


{% block content %}

    <p><label for="id_tasks_project_id">Проект:</label> <select name="tasks_project_id" id="id_tasks_project_id">
        <option value="" >---------</option>
        <option value="{{ task.tasks_project_id }}" selected>{{ task.tasks_project_id_id }}</option>

        <option value="11">Mantis</option>

        <option value="10">Bugzilla</option>

        <option value="12">BUGS - the Bug Genie</option>

        <option value="13">JIRA</option>

        <option value="3">Trac</option>

        <option value="1">Phoenix</option>

        <option value="2">Redmine</option>

        <option value="14">Easy Projects .NET</option>

    </select></p>
    <p><label for="id_tasks_tracker">Трекер:</label> <select name="tasks_tracker" id="id_tasks_tracker">
        <option value="{{ task.tasks_tracker }}" selected>{{ task.tasks_tracker }}</option>
        <option value="Bug">Bug</option>
        <option value="Feature">Feature</option>

        <option value="Support">Support</option>

    </select></p>
    <p><label for="id_tasks_title">Тема:</label> <input type="text" name="tasks_title" maxlength="100" required
                                                        id="id_tasks_title" value="{{ task.tasks_title }}" ></p>
    <p><label for="id_tasks_description">Описание:</label> <textarea name="tasks_description" cols="40" rows="10"
                                                                     maxlength="5000" id="id_tasks_description">
</textarea></p>
    <p><label for="id_tasks_status">Статус:</label> <select name="tasks_status" id="id_tasks_status">
        <option value="New" selected>New</option>

        <option value="In Progress">In Progress</option>

        <option value="Closed">Closed</option>

    </select></p>
    <p><label for="id_tasks_priority">Приоритет:</label> <select name="tasks_priority" id="id_tasks_priority">
        <option value="Low">Low</option>

        <option value="Normal" selected>Normal</option>

        <option value="High">High</option>

        <option value="Urgent">Urgent</option>

        <option value="Immediate">Immediate</option>

    </select></p>
    <p><label for="id_tasks_assigned">Назначена:</label> <input type="text" name="tasks_assigned" maxlength="50"
                                                                id="id_tasks_assigned"
                                                                value="{{ task.tasks_assigned }}"></p>
    <p><label for="id_tasks_category">Категория:</label> <input type="text" name="tasks_category" maxlength="50"
                                                                id="id_tasks_category"></p>
    <p><label for="id_tasks_files">Файлы:</label> <input type="file" name="tasks_files" id="id_tasks_files"></p>
    <p><label for="id_tasks_start_date">Начало выполнения:</label> <input type="text" name="tasks_start_date" required
                                                                          id="id_tasks_start_date"></p>
    <p><label for="id_tasks_complete_date">Дата выполнения:</label> <input type="text" name="tasks_complete_date"
                                                                           id="id_tasks_complete_date"></p>
    <p><label for="id_tasks_time_evaluation">Кол-во часов:</label> <input type="number" name="tasks_time_evaluation"
                                                                          value="0" id="id_tasks_time_evaluation"></p>
    <p><label for="id_tasks_prepared">Готовность:</label> <select name="tasks_prepared" id="id_tasks_prepared">
        <option value="">---------</option>

        <option value="0" selected>0%</option>

        <option value="10">10%</option>

        <option value="20">20%</option>

        <option value="30">30%</option>

        <option value="40">40%</option>

        <option value="50">50%</option>

        <option value="60">60%</option>

        <option value="70">70%</option>

        <option value="80">80%</option>

        <option value="90">90%</option>

        <option value="100">100%</option>

    </select></p>


{% endblock %}

projects/templates/projects/tasks_list.html
{% extends "base.html" %}

{% block title %}Задачи{% endblock %}


{% block content %}
    Всего задач: <b>{{ task_count }}</b> <br>
    {% if request.user.is_authenticated %}
        <a href="{% url 'taskadd' %}">
            <button type="button" class="btn btn-success">Добавить задачу</button>
        </a>
    {% endif %}
    {% if task_list %}

        <div class="table-responsive-sm">

            <table class="table table-sm table-hover">
                <thead class="thead-light">
                <tr>
                    <th style="text-align:center" scope="col">#</th>
                    <th style="text-align:center" scope="col">Проект</th>
                    <th style="text-align:center" scope="col">Трекер</th>
                    <th style="text-align:center" scope="col">Статус</th>
                    <th style="text-align:center" scope="col">Приоритет</th>
                    <th style="text-align:center" scope="col">Описание</th>
                    <th style="text-align:center" scope="col">Готовность</th>
                </tr>
                </thead>
                <tbody>

                {% for tasks in task_list %}
                    <tr>
                        <th style="text-align:center" scope="row"><a href="{% url 'project:task_view' tasks.id %}">{{ tasks.pk }}</a></th>
                        <td style="text-align:center">{% if tasks.tasks_project_id %}
                            {{ tasks.tasks_project_id }} {% else %} - {% endif %}</td>
                        <td style="text-align:center">{{ tasks.tasks_tracker }}</td>
                        <td style="text-align:center">{{ tasks.tasks_status }}</td>
                        <td style="text-align:center">{{ tasks.tasks_priority }}</td>
                        <td style="text-align:center"><a href="{% url 'project:task_view' tasks.id %}">{{ tasks.tasks_title }}</a></td>
                        <td style="text-align:center">{{ tasks.tasks_prepared }}%</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

            <nav aria-label="task_list">
                <ul class="pagination">

                    {% if project_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ task_list.previous_page_number }}">Назад</a>
                        </li>
                    {% endif %}

                    {% for num in task_list.paginator.page_range %}
                        {% if num == task_list.number %}
                            <li class="page-item active" aria-current="page"><span class="page-link">{{ num }} <span
                                    class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}"> <b>{{ num }}</b> </a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if task_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ task_list.next_page_number }}">
                            Далее
                        </a></li>
                    {% endif %}

                </ul>
            </nav>


        </div>

    {% endif %}
{% endblock %}